script: "rake spec"
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - jruby-19mode
  - rbx-2
install:
  - bundle install --retry=3
notifications:
  email:
    recipients:
      - developers@gocardless.com

